name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Spotbugs check
        run: ./gradlew spotbugsTest spotbugsMain

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  test:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Archive JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: JUnit test results
          path: build/test-results/test/**/*.xml

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: JUnit Tests report
          path: build/test-results/test/**/*.xml
          reporter: java-junit

      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v4
        with:
          name: Jacoco reports
          path: build/reports/jacoco

      - name: Archive Allure reports
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history